import requests
import json
import os
from datetime import datetime

def convert_epoch_to_date(epoch_time):
    date_time = datetime.fromtimestamp(epoch_time)
    formatted_date = date_time.strftime("%Y-%m-%d %H:%M:%S")
    return formatted_date

def list_converter(my_list):
    return my_list

BLOOM_KEY = os.environ.get('BLOOM_KEY')
BLOOM_HOST = os.environ.get('BLOOM_HOST')

url = "https://bloomberg-market-and-financial-news.p.rapidapi.com/news/list-by-region"

querystring = {"id":"asia-home-v3"}

headers = {
        "X-RapidAPI-Key": BLOOM_KEY,
        "X-RapidAPI-Host": BLOOM_HOST
}

response = requests.request("GET", url, headers=headers, params=querystring)
payload = response.json()



#with open("bb_regional.json","r") as JsonFileReaders:
#    file_content = JsonFileReaders.read()

#payload = json.loads(file_content)

for values in payload["modules"]:
    for newvalues in values["stories"]:
        print('Title: ', newvalues["title"])
        print('Summary: ', newvalues["summary"])
        print('Auto Generated Summary: ', newvalues["autoGeneratedSummary"])
        print('Published: ', convert_epoch_to_date(newvalues["published"]))
        print('UpdatedAt: ', convert_epoch_to_date(newvalues["updatedAt"]))
        print('Abstract: ', list_converter(newvalues["abstract"]))
        print('shortURL: ', newvalues["shortURL"])
        print('longURL: ', newvalues["longURL"])
        print("\n")
