# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DailyNews

on:
  schedule:
    - cron: "30 01 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tabulate Flask setuptools urllib3 Jinja2 forex-python
        pip --version
        python --version
        python3 --version
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate output
      run: echo "Hello, world!" > output.txt

    - name: telegram notify newsAPI
      run: python3 telegram_bot_newsAPI.py
      env:
        TELE_TOKEN: ${{ secrets.TELE_TOKEN }}

    - name: Generate output slack
      run: echo "@Nanoibot," > gnews.txt


    - name: news api
      run: python3 news.py >> gnews.txt
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

    - name: bloomberg regional news
      run: python3 bb_regional.py > bloomberg_all_news.txt
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        BLOOM_KEY: ${{ secrets.BLOOM_KEY }}
        BLOOM_HOST: ${{ secrets.BLOOM_HOST }}

    - name: sleep for 120 seconds
      run: |
        echo "Sleep"
        sleep 120

    - name: bloomberg markets news
      run: python3 bb_markets.py >> bloomberg_all_news.txt
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        BLOOM_KEY: ${{ secrets.BLOOM_KEY }}
        BLOOM_HOST: ${{ secrets.BLOOM_HOST }}

    - name: sleep for 120 seconds
      run: |
        echo "Sleep"
        sleep 120

    - name: bloomberg markets news
      run: python3 bb_finance.py >> bloomberg_all_news.txt
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        BLOOM_KEY: ${{ secrets.BLOOM_KEY }}
        BLOOM_HOST: ${{ secrets.BLOOM_HOST }}

    - name: telegram bloomberg news notification
      run: python3 telegram_bot_bb_all.py
      env:
        TELE_TOKEN: ${{ secrets.TELE_TOKEN }}
