# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "25 00 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tabulate Flask setuptools urllib3 Jinja2 forex-python
        pip --version
        python --version
        python3 --version
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate output
      run: echo "Hello, world!" > output.txt

    - name: news api
      run: python3 news.py > gnews.txt
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

    - name: bloomberg news api
      run: python3 bloombergv1.py > bloombergv1news.txt
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        BLOOM_KEY: ${{ secrets.BLOOM_KEY }}
        BLOOM_HOST: ${{ secrets.BLOOM_HOST }}

    - name: sleep for 120 seconds
      run: |
        echo "Sleep"
        sleep 120

    - name: required bloomberg news api
      run: python3 bloombergv2.py >> bloombergv1news.txt
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        BLOOM_KEY: ${{ secrets.BLOOM_KEY }}
        BLOOM_HOST: ${{ secrets.BLOOM_HOST }}

    - name: slack notification
      run: python3 slacker_bloom.py
      env:
        SLACK1: ${{ secrets.SLACK1 }}
        SLACK2: ${{ secrets.SLACK2 }}
        SLACK3: ${{ secrets.SLACK3 }}

    - name: sleep for 120 seconds
      run: |
        echo "Sleep"
        sleep 60

    - name: slack notification
      run: python3 slacker_gnews.py
      env:
        SLACK1: ${{ secrets.SLACK1 }}
        SLACK2: ${{ secrets.SLACK2 }}
        SLACK3: ${{ secrets.SLACK3 }}
